- name: Rules with kafka as source
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        topic: network
        host: containers.ansible-automates.co.za
        port: 9092

  rules:
    - name: Retrieve Data and Launch Job-template
      condition: events.body.fields.new_state == "interface-notif-state-down" and events.body.fields.if_name in vars.protected
      action:
        run_job_template:
          name: "EDA-Fix-Ports"
          organization: "Default"
          job_args:
            extra_vars:
              interface: "{{ event.body.fields.if_name }}"
              rtr: "{{ event.body.fields.host_name }}"
